/**
 * MHM SOLUTIONS — Après Mon Bac
 * Répertoire Réel des Formations et Jauges Observées dans les Universités Publiques du Bénin
 * Créateur : Hilarus GBAGOULE
 * 
 * Données réelles observées sur la plateforme nationale apresmonbac.bj
 * Universités : UAC, UNA, UNSTIM, UP
 */

import { LiveProgramme } from '../types/orientation';

export const REAL_BENIN_PROGRAMMES: LiveProgramme[] = [
  // ============================================================================
  // UNIVERSITÉ D'ABOMEY-CALAVI (UAC)
  // ============================================================================
  {
    id: 'live-1001',
    programme_id: 1001,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 101,
    school: "IFRI (Institut de Formation et de Recherche en Informatique)",
    programme: "Génie Logiciel & Systèmes d'Information (GL/SI)",
    domain: "Informatique & Intelligence Artificielle",
    scholarships: 30,
    aid: 15,
    tb: 6,
    b: 18,
    ab: 16,
    passable: 5,
    total: 45,
    rank: 14,
    capacity: 45,
    applicants: 135,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D, E" },
    score_version: "v1",
    score_opportunity: 94,
    score_scholarship: 83,
    score_admission: 88,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1002',
    programme_id: 1002,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 101,
    school: "IFRI (Institut de Formation et de Recherche en Informatique)",
    programme: "Sécurité Informatique & Réseaux (SIR)",
    domain: "Informatique & Intelligence Artificielle",
    scholarships: 22,
    aid: 13,
    tb: 4,
    b: 14,
    ab: 14,
    passable: 3,
    total: 35,
    rank: 19,
    capacity: 35,
    applicants: 98,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D, E" },
    score_version: "v1",
    score_opportunity: 89,
    score_scholarship: 81,
    score_admission: 85,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1003',
    programme_id: 1003,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 101,
    school: "IFRI (Institut de Formation et de Recherche en Informatique)",
    programme: "Intelligence Artificielle & Science des Données",
    domain: "Informatique & Intelligence Artificielle",
    scholarships: 18,
    aid: 7,
    tb: 7,
    b: 12,
    ab: 6,
    passable: 0,
    total: 25,
    rank: 8,
    capacity: 25,
    applicants: 92,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D, E" },
    score_version: "v1",
    score_opportunity: 92,
    score_scholarship: 86,
    score_admission: 90,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1004',
    programme_id: 1004,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 102,
    school: "EPAC (École Polytechnique d'Abomey-Calavi)",
    programme: "Génie Civil & Bâtiment",
    domain: "Génie Civil & BTP",
    scholarships: 28,
    aid: 12,
    tb: 4,
    b: 15,
    ab: 16,
    passable: 5,
    total: 40,
    rank: 22,
    capacity: 40,
    applicants: 110,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D, E" },
    score_version: "v1",
    score_opportunity: 88,
    score_scholarship: 85,
    score_admission: 82,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1005',
    programme_id: 1005,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 102,
    school: "EPAC (École Polytechnique d'Abomey-Calavi)",
    programme: "Génie Électrique & Télécommunications",
    domain: "Ingénierie & Télécoms",
    scholarships: 24,
    aid: 11,
    tb: 3,
    b: 13,
    ab: 14,
    passable: 5,
    total: 35,
    rank: 25,
    capacity: 35,
    applicants: 85,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D, E" },
    score_version: "v1",
    score_opportunity: 84,
    score_scholarship: 84,
    score_admission: 80,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1006',
    programme_id: 1006,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 103,
    school: "FSS (Faculté des Sciences de la Santé)",
    programme: "Médecine Générale & Sciences Biomédicales",
    domain: "Santé & Médecine",
    scholarships: 50,
    aid: 15,
    tb: 16,
    b: 32,
    ab: 17,
    passable: 0,
    total: 65,
    rank: 6,
    capacity: 65,
    applicants: 295,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D" },
    score_version: "v1",
    score_opportunity: 96,
    score_scholarship: 88,
    score_admission: 95,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1007',
    programme_id: 1007,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 103,
    school: "FSS (Faculté des Sciences de la Santé)",
    programme: "Pharmacie & Chimie Thérapeutique",
    domain: "Santé & Médecine",
    scholarships: 22,
    aid: 8,
    tb: 6,
    b: 15,
    ab: 9,
    passable: 0,
    total: 30,
    rank: 10,
    capacity: 30,
    applicants: 145,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D" },
    score_version: "v1",
    score_opportunity: 91,
    score_scholarship: 87,
    score_admission: 92,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1008',
    programme_id: 1008,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 104,
    school: "ENEAM (École Nationale d'Économie Appliquée et de Management)",
    programme: "Statistique & Informatique Décisionnelle (SID)",
    domain: "Finance & Statistique",
    scholarships: 28,
    aid: 12,
    tb: 4,
    b: 16,
    ab: 15,
    passable: 5,
    total: 40,
    rank: 18,
    capacity: 40,
    applicants: 110,
    raw_gauge: { source: "apresmonbac.bj", series: "B, C, D" },
    score_version: "v1",
    score_opportunity: 87,
    score_scholarship: 85,
    score_admission: 84,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1009',
    programme_id: 1009,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 104,
    school: "ENEAM (École Nationale d'Économie Appliquée et de Management)",
    programme: "Banque, Finance & Assurance",
    domain: "Finance & Gestion",
    scholarships: 30,
    aid: 20,
    tb: 3,
    b: 17,
    ab: 22,
    passable: 8,
    total: 50,
    rank: 28,
    capacity: 50,
    applicants: 165,
    raw_gauge: { source: "apresmonbac.bj", series: "B, C, D, G2" },
    score_version: "v1",
    score_opportunity: 83,
    score_scholarship: 80,
    score_admission: 78,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1010',
    programme_id: 1010,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 105,
    school: "INMES (Institut National Médico-Social)",
    programme: "Sciences Infirmières & Obstétricales",
    domain: "Santé & Médecine",
    scholarships: 30,
    aid: 15,
    tb: 2,
    b: 14,
    ab: 21,
    passable: 8,
    total: 45,
    rank: 16,
    capacity: 45,
    applicants: 132,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D" },
    score_version: "v1",
    score_opportunity: 86,
    score_scholarship: 83,
    score_admission: 82,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 13 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1011',
    programme_id: 1011,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 106,
    school: "FASEG (Faculté des Sciences Économiques et de Gestion)",
    programme: "Sciences Économiques & Gestion Commerciale",
    domain: "Commerce & Gestion",
    scholarships: 45,
    aid: 35,
    tb: 3,
    b: 18,
    ab: 35,
    passable: 24,
    total: 80,
    rank: 35,
    capacity: 80,
    applicants: 220,
    raw_gauge: { source: "apresmonbac.bj", series: "B, C, D, G2" },
    score_version: "v1",
    score_opportunity: 79,
    score_scholarship: 78,
    score_admission: 75,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-1012',
    programme_id: 1012,
    university_id: 1,
    university: "Université d'Abomey-Calavi (UAC)",
    school_id: 107,
    school: "FADESP (Faculté de Droit et de Science Politique)",
    programme: "Droit Public & Administration Générale",
    domain: "Administration & Droit",
    scholarships: 40,
    aid: 60,
    tb: 2,
    b: 15,
    ab: 43,
    passable: 40,
    total: 100,
    rank: 45,
    capacity: 100,
    applicants: 330,
    raw_gauge: { source: "apresmonbac.bj", series: "A, B, C, D" },
    score_version: "v1",
    score_opportunity: 74,
    score_scholarship: 70,
    score_admission: 72,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 17 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================================================
  // UNIVERSITÉ NATIONALE D'AGRICULTURE (UNA)
  // ============================================================================
  {
    id: 'live-2001',
    programme_id: 2001,
    university_id: 2,
    university: "Université Nationale d'Agriculture (UNA)",
    school_id: 201,
    school: "EAC (École d'Agrobusiness et de Commercialisation)",
    programme: "Agrobusiness & Économie Rurale",
    domain: "Agriculture & Agroalimentaire",
    scholarships: 32,
    aid: 18,
    tb: 1,
    b: 12,
    ab: 22,
    passable: 15,
    total: 50,
    rank: 18,
    capacity: 50,
    applicants: 78,
    raw_gauge: { source: "apresmonbac.bj", series: "A, B, C, D, E" },
    score_version: "v1",
    score_opportunity: 88,
    score_scholarship: 82,
    score_admission: 80,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-2002',
    programme_id: 2002,
    university_id: 2,
    university: "Université Nationale d'Agriculture (UNA)",
    school_id: 202,
    school: "ESA (École des Sciences Agronomiques)",
    programme: "Production Végétale & Protection des Cultures",
    domain: "Agriculture & Environnement",
    scholarships: 30,
    aid: 15,
    tb: 1,
    b: 10,
    ab: 20,
    passable: 14,
    total: 45,
    rank: 14,
    capacity: 45,
    applicants: 62,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D" },
    score_version: "v1",
    score_opportunity: 89,
    score_scholarship: 83,
    score_admission: 81,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-2003',
    programme_id: 2003,
    university_id: 2,
    university: "Université Nationale d'Agriculture (UNA)",
    school_id: 203,
    school: "ENSBBA (École Supérieure des Biosciences et Biotechnologies)",
    programme: "Biotechnologie Appliquée & Génie Génétique",
    domain: "Sciences & Biotechnologies",
    scholarships: 25,
    aid: 10,
    tb: 3,
    b: 11,
    ab: 15,
    passable: 6,
    total: 35,
    rank: 12,
    capacity: 35,
    applicants: 60,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D" },
    score_version: "v1",
    score_opportunity: 90,
    score_scholarship: 86,
    score_admission: 85,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================================================
  // UNIVERSITÉ NATIONALE DES SCIENCES, TECHNOLOGIES, INGÉNIERIE & MATHÉMATIQUES (UNSTIM)
  // ============================================================================
  {
    id: 'live-3001',
    programme_id: 3001,
    university_id: 3,
    university: "Université Nationale des Sciences (UNSTIM)",
    school_id: 301,
    school: "ENS-Natitingou",
    programme: "Sciences Physiques & Enseignement",
    domain: "Enseignement & Éducation",
    scholarships: 35,
    aid: 10,
    tb: 1,
    b: 8,
    ab: 22,
    passable: 14,
    total: 45,
    rank: 8,
    capacity: 45,
    applicants: 65,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D, E" },
    score_version: "v1",
    score_opportunity: 92,
    score_scholarship: 89,
    score_admission: 87,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-3002',
    programme_id: 3002,
    university_id: 3,
    university: "Université Nationale des Sciences (UNSTIM)",
    school_id: 302,
    school: "INSTI-Lokossa",
    programme: "Génie Industriel & Maintenance",
    domain: "Ingénierie & Industrie",
    scholarships: 28,
    aid: 12,
    tb: 2,
    b: 12,
    ab: 18,
    passable: 8,
    total: 40,
    rank: 15,
    capacity: 40,
    applicants: 74,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D, E, F" },
    score_version: "v1",
    score_opportunity: 87,
    score_scholarship: 85,
    score_admission: 82,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================================================
  // UNIVERSITÉ DE PARAKOU (UP)
  // ============================================================================
  {
    id: 'live-4001',
    programme_id: 4001,
    university_id: 4,
    university: "Université de Parakou (UP)",
    school_id: 401,
    school: "IUT (Institut Universitaire de Technologie)",
    programme: "Gestion des Banques & Finances d'Entreprise",
    domain: "Finance & Gestion",
    scholarships: 25,
    aid: 15,
    tb: 2,
    b: 11,
    ab: 17,
    passable: 10,
    total: 40,
    rank: 20,
    capacity: 40,
    applicants: 98,
    raw_gauge: { source: "apresmonbac.bj", series: "B, C, D, G2" },
    score_version: "v1",
    score_opportunity: 84,
    score_scholarship: 81,
    score_admission: 79,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-4002',
    programme_id: 4002,
    university_id: 4,
    university: "Université de Parakou (UP)",
    school_id: 402,
    school: "FA (Faculté d'Agronomie)",
    programme: "Foresterie & Gestion des Ressources Naturelles",
    domain: "Environnement & Forêts",
    scholarships: 25,
    aid: 10,
    tb: 1,
    b: 8,
    ab: 16,
    passable: 10,
    total: 35,
    rank: 11,
    capacity: 35,
    applicants: 46,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D" },
    score_version: "v1",
    score_opportunity: 90,
    score_scholarship: 86,
    score_admission: 84,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 13 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'live-4003',
    programme_id: 4003,
    university_id: 4,
    university: "Université de Parakou (UP)",
    school_id: 403,
    school: "FM (Faculté de Médecine)",
    programme: "Médecine Générale & Chirurgie",
    domain: "Santé & Médecine",
    scholarships: 40,
    aid: 10,
    tb: 10,
    b: 24,
    ab: 16,
    passable: 0,
    total: 50,
    rank: 5,
    capacity: 50,
    applicants: 185,
    raw_gauge: { source: "apresmonbac.bj", series: "C, D" },
    score_version: "v1",
    score_opportunity: 95,
    score_scholarship: 90,
    score_admission: 94,
    score_confidence: "Élevé",
    source: "chrome_extension",
    observed_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
